theme = "ao"

[editor]
bufferline = "multiple"
cursorline = true
rulers = [120]
end-of-line-diagnostics = "hint"
true-color = true
line-number = "relative"
color-modes = true
auto-pairs = true
# gutters = ["diff", "line-numbers"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.insert.j]
k = "normal_mode" # Maps `jk` to exit insert mode

[keys.normal.space]
w = ":write"
q = ":quit"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
H = ":buffer-previous"
L = ":buffer-next"
X = "select_line_above"
C-h = "jump_view_left" # switching panes
C-l = "jump_view_right"
ret = "goto_word" # shortcut for gw
# ";" = "@A;<esc>"

# Match in next instance of pair
[keys.normal.m.n]
"(" = "@s\\(<ret>nmim"
"{" = "@s\\{<ret>nmim"
"[" = "@s\\[<ret>nmim"
'"' = '@s\"<ret>nmim'
"'" = "@s\\'<ret>nmim"
"<" = "@s<lt><ret>nmim"

# Match in previous instance of pair
[keys.normal.m.p]
"(" = "@s\\)<ret>Nmmmim"
"{" = "@s\\}<ret>Nmmmim"
"[" = "@s\\]<ret>Nmmmim"
'"' = '@s\"<ret>Nmmmim'
"'" = "@s\\'<ret>Nmmmim"
"<" = "@s<gt><ret>Nmmmim"

[keys.select]
ret = "extend_to_word"
X = "select_line_above"

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["diagnostics", "selections", "register", "position", "file-encoding", "version-control"]

[editor.inline-diagnostics]
cursor-line = "error" # Show inline diagnostics when the cursor is on the line
other-lines = "disable" # Don't expand diagnostics unless the cursor is on the line
